server:
  port: 31302
spring:
  application:
    name: bl-service-cms-client
  data:
    mongodb:
      uri: mongodb://nixstack:root@192.168.235.102:27017/bl_cms
      database: bl_cms
#logging.level.org.springframework.boot.autoconfigure: ERROR
  rabbitmq:
    host: 192.168.235.102
    port: 5672
    username: admin
    password: admin
    virtualHost: /
boundless:
  mq:
    #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_01
    routingKey: 5a751fab6abb5044e0d19ea1	#此routingKey为门户站点ID
#    routingKey: 5d9c00957c2c5d533fcc8ddb    #此routingKey为课程详情站点ID