server:
  port: ${PORT:39101} # 环境参数
spring:
  application:
    name: bl-govern-center
eureka:
  client:
    registerWithEureka: false #服务注册，是否将自己注册到Eureka服务中
    fetchRegistry: false #服务发现，是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端的交互地址，高可用状态配置对方的地址，单机状态配置自己（如果不配置则默认本机8761端口）
      defaultZone: ${EUREKA_SERVER:http://127.0.0.1:39101/eureka/}
#      defaultZone: ${EUREKA_SERVER:eureka02:39101/eureka/}
  server:
    enable-self-preservation: false #是否开启自我保护模式：开发环境下关闭，因为会频繁启动服务；生产环境打开
    eviction-interval-timer-in-ms: 60000 #服务注册表清理间隔（单位毫秒，默认是60*1000）
#  instance:
#    hostname: ${EUREKA_DOMAIN:eureka01}
