server:
  port: 31303
spring:
  application:
    name: bl-service-course
  datasource:
    druid:
      url: jdbc:mysql://192.168.235.102:3306/bl_course?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:39101/eureka/}
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
course-publish:
  #siteId: 5a751fab6abb5044e0d19ea1 #门户主站
  siteId: 5d9c00957c2c5d533fcc8ddb  #课程详情
  templateId: 5d9b495a7c2c5d533fcc8d9c #自定义课程详情页测试模版
  previewUrl: http://www.nixstack.com/cms/page/preview/
  pageWebPath: /course/detail/
  pagePhysicalPath: /course/detail/
  dataUrlPre: http://localhost:31303/api/course/view/
logging.level.org.springframework.boot.autoconfigure: ERROR
#logging.level.org.springframework.boot.autoconfigure: ERROR